# Generated by Django 4.2.9 on 2024-02-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
