# Generated by Django 4.2.9 on 2024-03-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_tournement_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='unknown', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tournement_username',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
