# Generated by Django 5.0.3 on 2024-03-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_authenticated',
            new_name='is_student',
        ),
    ]
