version: '3'

services:

  web:
    build: ./
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./src:/src
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_data:
