# Generated by Django 4.2.9 on 2024-02-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_losses_profile_matches_profile_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='losses',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
