# Generated by Django 4.2.9 on 2024-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_losses_alter_profile_matches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='losses',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
